# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 663)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Crackers_Button = QtWidgets.QToolButton(self.centralwidget)
        self.Crackers_Button.setGeometry(QtCore.QRect(0, 0, 211, 19))
        self.Crackers_Button.setObjectName("Crackers_Button")
        self.Miners_Button = QtWidgets.QToolButton(self.centralwidget)
        self.Miners_Button.setGeometry(QtCore.QRect(212, 0, 211, 19))
        self.Miners_Button.setObjectName("Miners_Button")
        self.Useful_Button = QtWidgets.QToolButton(self.centralwidget)
        self.Useful_Button.setGeometry(QtCore.QRect(425, 0, 211, 19))
        self.Useful_Button.setObjectName("Useful_Button")
        self.Spies_Button = QtWidgets.QToolButton(self.centralwidget)
        self.Spies_Button.setGeometry(QtCore.QRect(638, 0, 211, 19))
        self.Spies_Button.setObjectName("Spies_Button")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setEnabled(True)
        self.comboBox.setGeometry(QtCore.QRect(0, 90, 201, 31))
        self.comboBox.setMouseTracking(False)
        self.comboBox.setEditable(False)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Crackers_Button.setText(_translate("MainWindow", "Crackers"))
        self.Miners_Button.setText(_translate("MainWindow", "Miners"))
        self.Useful_Button.setText(_translate("MainWindow", "Useful"))
        self.Spies_Button.setText(_translate("MainWindow", "Spies"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Фишер"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Брутфорс"))
